#!/usr/bin/env bash

set -eux

git init

# https://sourceforge.net/projects/bbcodelib/files/OldFiles/
unzip ~/Downloads/bbcodelib.zip
git add .
GIT_COMMITTER_NAME="Igor Franchuk" GIT_COMMITTER_EMAIL="sprog@online.ru" GIT_COMMITTER_DATE="2007-12-19 19:46:58 UTC" git commit  --author="Igor Franchuk <sprog@online.ru>" --date="2007-12-19 19:46:58 UTC"  -m "version 1.0.0"

# https://sourceforge.net/projects/bbcodelib/files/bbcodelib/bbcodelib%201.4.1/
git rm -rf .
unzip  ~/Downloads/bbcodelib_1_4_1.zip
git add .
GIT_COMMITTER_NAME="Igor Franchuk" GIT_COMMITTER_EMAIL="sprog@online.ru" GIT_COMMITTER_DATE="2008-01-03 02:23:38 UTC" git commit  --author="Igor Franchuk <sprog@online.ru>" --date="2008-01-03 02:23:38 UTC"  -m "version 1.4.1"

# https://sourceforge.net/projects/bbcodelib/files/bbcodelib/bbcode%20library%201.4.7/
git rm -rf .
unzip ~/Downloads/bbcodelib_147.zip
git add .
GIT_COMMITTER_NAME="Igor Franchuk" GIT_COMMITTER_EMAIL="sprog@online.ru" GIT_COMMITTER_DATE="2008-07-01 12:15:52 UTC" git commit  --author="Igor Franchuk <sprog@online.ru>" --date="2008-07-01 12:15:52 UTC"  -m "version 1.4.7"

# https://sourceforge.net/projects/bbcodelib/
# License: GNU General Public License version 2.0 (GPLv2)
wget https://github.com/licenses/license-templates/raw/refs/heads/master/templates/gpl2.txt
mv gpl2.txt license.txt
git add license.txt
git commit -m "add license.txt"

# generated by https://chatgpt.com/ from bbcodelib/bbcodelib.vcproj
# see also bbcodelib/bbcodelib.mak
cp ../CMakeLists.txt .
git add CMakeLists.txt
git commit -m "add CMakeLists.txt"

# fix build errors
patch -p1 <../todo.patch
git commit -a -m "remove throw from function prototypes"

# build
mkdir build
cd build/
cmake ..
make

# test
cp ../testsuite/message.bb .
./testsuite/bbcodelib_test

# clean
cd ..
rm -rf build/
